version: '3.4'
services:
 app:
    environment: 
        CHOKIDAR_USEPOLLING: "true"
    container_name: "app"
    image: "docker.pkg.github.com/al3xdiaz/cajeroautomatico/app:latest"
    build:
        context: .
        dockerfile: app/dockerfile.test
#        dockerfile: app/dockerfile.prod
    ports: 
        - "3000:3000"
    #restart: always
    volumes: 
        - "./app/src:/code/src"
        - "./app/public:/code/public"